[package]
name = "emoji"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mindus = { version = "5.0.14", default-features = false }
phf = { version = "0.11.2", features = ["macros"] }
